import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { classMerge } from '@/util/classMerge';
import './globals.css';

const roboto = Roboto({
  weight: ['400', '100', '300', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={classMerge(
          roboto.className,
          'flex justify-center items-center dark:bg-[#141D2F]'
        )}
      >
        {children}
      </body>
    </html>
  );
}
